# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45a5934b5ccff1914ecc12cdf79d1b213a52c959add958fd40958e6fe4eb68e6a86e4601388d630e6bd8d8d44a96eb2999f26b126f7526590ac26f44920e812

test:
  secret_key_base: 05158bd1ba8ebc6b6498b5bcea14ffb8a75217e2c6f2d7b72aee7742fa5fcad2ae2b6ad74f6373c2f76767d8d79ffaf396cedbd00c34fa92944df0dbf09c4cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
